config/routes.rb
Webgrouper::Application.routes.draw do

  resources :statistics, only: :index do
    collection do
      get 'webgrouper_patient_cases'
      get 'batchgrouper_queries'
      get 'webapi_queries'
      get 'tarpsy_patient_cases'
      get 'tarpsy_batchgrouper_queries'
    end
  end

  scope "/:locale" do
    resources :webgrouper_patient_cases, only: [:index, :new, :create] do
      collection do
        patch '/' => 'webgrouper_patient_cases#create'
        match 'parse', via: [:get, :post]
      end
    end
    resources :tarpsy_patient_cases, only: [:index, :new, :create] do
      collection do
        patch '/' => 'tarpsy_patient_cases#create'
        get 'generate_random' => 'tarpsy_patient_cases#generate_random'
      end
    end
    resources :tarpsy_batchgrouper_queries, only: [:index, :new, :create] do
      collection do
        patch '/' => 'tarpsy_batchgrouper_queries#create'
      end
    end
    resources :batchgrouper_queries, only: [:index, :new, :create] do
      collection do
        patch '/' => 'batchgrouper_queries#create'
      end
    end
    match 'parse' => 'webgrouper_patient_cases#parse', via: [:get, :post]
    get 'help' => 'static_pages#help'
    get 'tos' => 'static_pages#tos'
    get 'autocomplete_icd_code' => 'webgrouper_patient_cases#autocomplete_icd_code'
    get 'autocomplete_chop_code' => 'webgrouper_patient_cases#autocomplete_chop_code'
  end

  resources :webapi_queries, path: 'webapi', as: 'webapi', only: [:index, :create] do
    collection do
      match 'group', via: [:get, :post]
      match 'systems', via: [:get, :post]
    end
  end

  get 'grouper' => 'batchgrouper_queries#tos'
  get 'activate_beta' => 'webgrouper_patient_cases#activate_beta'
  get 'batchgrouper' => 'batchgrouper_queries#tos'
  get 'webgrouper' => 'webgrouper_patient_cases#tos'
  get 'about' => 'static_pages#about'

  # Visitors of tarps.swissdrg.org should be redirected to tarpsy form.
  constraints subdomain: 'tarpsy' do
    get '/' => 'tarpsy_patient_cases#tos'
  end

  root :to => 'webgrouper_patient_cases#tos'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404', via: [:get, :post]
  end
end

app/controllers/webgrouper_patient_cases_controller.rb
class WebgrouperPatientCasesController < ApplicationController

  def autocomplete_code(model)
    term = params[:term]
    version = params[:version]
    # Find 10 matching codes, either by matching text, code or code_short
    codes = model.where(version: version)
                .any_of({text: /#{term}/i}, {code: /^#{term}/i}, {code_short: /^#{term}/i})
                .order_by(:code.asc)
                .limit(10)
    render :json => codes.map { |code| {:label => "#{code.code} #{code.text}", :code => code.code, text: code.text} }
  end

  def autocomplete_icd_code
    autocomplete_code(Icd)
  end

  def autocomplete_chop_code
    autocomplete_code(Chop)
  end

  def index
    redirect_to action: :new
  end

  def tos
    @link = new_webgrouper_patient_case_path
    render 'static_pages/tos'
  end
  
  def new
    @webgrouper_patient_case = WebgrouperPatientCase.new
    render 'form'
  end

  def parse
    # For legacy reasons, we build valid params from this (still used in fallabfrage):
    if params[:pc]
      params[:webgrouper_patient_case_parsing] = { parse_string: params[:pc][:string]}
    end
    if params[:webgrouper_patient_case_parsing].present?
      @webgrouper_patient_case_parsing = WebgrouperPatientCaseParsing.new(params[:webgrouper_patient_case_parsing])
      if @webgrouper_patient_case_parsing.valid?
        @webgrouper_patient_case = @webgrouper_patient_case_parsing.to_patient_case
        if @webgrouper_patient_case.valid?
          group(@webgrouper_patient_case)
        end
        render 'form'
      end
    else
      @webgrouper_patient_case_parsing = WebgrouperPatientCaseParsing.new
    end
  end

  def create
    @webgrouper_patient_case = WebgrouperPatientCase.create(webgrouper_patient_case_params)
    if @webgrouper_patient_case.errors.empty?
      group(@webgrouper_patient_case)
    end
    render 'form'
  end

  # For testing new systems, exclusive users are given this url. This activates the beta for the current session,
  # then sends the user to the grouper interface
  def activate_beta
    session[:beta] = true
    flash[:popup] = { body: I18n.t('flash.beta.body'), title: I18n.t('flash.beta.title') }
    redirect_to :action => 'index'
  end

  private

  def webgrouper_patient_case_params
    params[:webgrouper_patient_case].permit(:system_id, :house, :entry_date, :exit_date, :leave_days,
                                            :adm, :sep, :los, :sex, :birth_date, :age, :adm_weight,
                                            :hmv, :pdx, :age_mode, :age_mode_decoy,
                                            diagnoses: [], procedures: [:c, :l, :d])
  end

  def group(patient_case)
    begin
      start = Time.now
      @factor = 10000
      # Supplements computation is disabled for now.
      @supplement_procedures = Hash.new
      @pc = patient_case.to_java
      grouper, catalogue = patient_case.system.grouper_and_catalogue
      grouper.groupByReference(@pc)
      @result = @pc.getGrouperResult()
      @webgrouper_patient_case.drg_code = @result.drg
      @weighting_relation = catalogue.get(@result.drg)
      @weighting_relation.extend(WeightingRelation)

      @cost_weight = grouper.calculateEffectiveCostWeight(@pc, @weighting_relation)

      @los_chart = LosDataTable.new(@pc.los, @cost_weight, @weighting_relation, @factor).make_chart
      Rails.logger.info("Grouped patient case in #{Time.now - start}")
    rescue Exception => e
      flash[:error] = e.message
      Rails.logger.error e.message
      Rails.logger.error e.backtrace.join("\n")
      if Rails.env == 'development'
        raise e
      end
    end
  end

end

app/helpers/webgrouper_patient_cases_helper.rb
module WebgrouperPatientCasesHelper
  # valid types are: drgs, mdcs, adrgs, tables, icd_codes, chop_codes, functions
  # (given as strings)
  def link_to_online_definition_manual(code, type, system)
    manual_url = system.manual_url
    if manual_url.blank?
      code
    else
      link_to code, manual_url + type.to_s + "/name?code=" + code + "&locale=" + I18n.locale.to_s, :title => t('to_online_definition_manual')
    end
  end

  def parse_url_for(patient_case)
    parse_webgrouper_patient_cases_url(webgrouper_patient_case_parsing: {parse_string: patient_case.to_url_string})
  end

  java_import org.swissdrg.grouper.GrouperResult

  def normal_group?
    @result.gst == GrouperResult::GSTFlag::NORMAL_GROUP
  end
end

app/views/webgrouper_patient_cases/_diagnoses.html.haml
- necessary_rows = [(@webgrouper_patient_case.diagnoses.size.to_f / 5).ceil, 1].max
- count = 0
- necessary_rows.times do |row|
  .diagnoses_row
    = row > 0 ? content_tag(:label, '') : ''
    .sameline
      - 5.times do
        %span.field{class: ('field_with_errors' if @webgrouper_patient_case.diagnoses_errors[count])}
          = autocomplete_field_tag "webgrouper_patient_case[diagnoses][]",
                            @webgrouper_patient_case.diagnoses[count],
                            autocomplete_icd_code_path(version: @webgrouper_patient_case.system.icd_version),
                            class: 'autocomplete small_field diagnosis inc_clone_id',
                            id: "webgrouper_patient_case_diagnoses_#{count}"
          - count += 1
        .spacer
      .spacer
      - if row == 0
        .dynamic_field_buttons
          = image_tag('bullet_toggle_plus.png',  class: 'add_diagnoses_row')
          = image_tag('bullet_toggle_minus.png', class: 'remove_diagnoses_row')

app/views/webgrouper_patient_cases/_error_messages.html.haml
- if @webgrouper_patient_case.errors.any?
  .errorflash
    %h2
      = t 'errors.template.body'
    %ul
      - @webgrouper_patient_case.errors.each do |attr, msg|
        %li
          = t("simple_form.labels.defaults." + attr.to_s) + " " + msg

- if flash[:error].present?
  .errorflash
    = flash[:error]

- if flash[:info].present?
  .info
    = flash[:info]

- if flash[:popup].present?
  .flash-popup{ title: flash[:popup][:title]}
    = simple_format flash[:popup][:body]

app/views/webgrouper_patient_cases/_procedures.html.haml
- necessary_rows = [(@webgrouper_patient_case.procedures.size.to_f / 3).ceil, 1].max
- count = 0
- necessary_rows.times do |row|
  .procedures_row
    = row > 0 ? content_tag(:label, '') : ''
    .sameline
      - 3.times do
        %span.field
          - procedure_hash = @webgrouper_patient_case.procedures[count] || {}
          = autocomplete_field_tag 'webgrouper_patient_case[procedures][][c]',
                                 procedure_hash['c'],
                                 autocomplete_chop_code_path(version: @webgrouper_patient_case.system.chop_version),
                                 :class => 'autocomplete small_field inc_clone_id',
                                 :id => "webgrouper_patient_case_procedures_#{count}_c"
          = select_tag 'webgrouper_patient_case[procedures][][l]',
                            options_for_select(["", "R", "L", "B"], procedure_hash['l']),
                            :class => 'tiny_field',
                            :id => "webgrouper_patient_case_procedures_#{count}_l"
          = text_field_tag 'webgrouper_patient_case[procedures][][d]',
                           procedure_hash['d'],
                           :class => 'small_field date_picker',
                           :id => "webgrouper_patient_case_procedures_#{count}_d"
          - count += 1
      - if row == 0
        .dynamic_field_buttons
          = image_tag('bullet_toggle_plus.png',  class: 'add_procedures_row')
          = image_tag('bullet_toggle_minus.png', class: 'remove_procedures_row')

app/views/webgrouper_patient_cases/form.html.haml
= content_for :header do
  = javascript_include_tag 'https://www.google.com/jsapi'
  = javascript_include_tag 'webgrouper'
- content_for :title, 'Webgrouper'
= render "shared/error_messages", :errors => @webgrouper_patient_case.errors

= simple_form_for @webgrouper_patient_case, url: webgrouper_patient_cases_path,
                  defaults: { placeholder: false, hint: false } do |f|
  .span-24
    = render 'shared/system', :f => f,
                              :current_system => @webgrouper_patient_case.system,
                              :house => @webgrouper_patient_case.house
  .span-12
    %fieldset#stay
      %legend= t("fieldsets.stay")
      = f.input :entry_date, as: :date_picker, input_html: { :class => "calc_los" }
      = f.input :exit_date, as: :date_picker, input_html: { :class => "calc_los" }
      = f.input :leave_days, 
                :input_html => { :class => "calc_los numeric" }
      = f.input :adm, 
                :as => :select, 
                :include_blank => false,
                :collection => WebgrouperPatientCase::ADMISSION_MODES,
                :label_method => lambda { |el| t "simple_form.options.webgrouper_patient_case.adm.adm#{el}" }
      = f.input :sep, 
                :as => :select, 
                :include_blank => false,
                :collection => WebgrouperPatientCase::SEPARATION_MODES,
                :label_method => lambda { |el| t "simple_form.options.webgrouper_patient_case.sep.sep#{el}" }
      = f.input :los,
                :input_html => { :class => "numeric" }
  .span-12.last
    %fieldset#patient-data
      %legend= t("fieldsets.patient_data")
      = f.input :sex,
                :collection => WebgrouperPatientCase::SEX_MODES,
                :include_blank => false,
                :label_method => lambda { |el| t "simple_form.options.webgrouper_patient_case.sex.#{el}" }
      = f.input :birth_date, as: :date_picker
      .sameline
        = f.input :age,
                  :input_html => { :class => "numeric" }
        = f.input :age_mode_decoy,
                  :as => :select,
                  :collection => [:years, :days],
                  :include_blank => false,
                  :input_html => { :onchange => "admWeightControl(80)"},
                  :label => false
        / hidden field which contains the real value for age_mode in case age_mode_decoy is disabled
        = f.input :age_mode,
                  :as => :hidden,
                  :collection => [:years, :days],
                  :include_blank => false,
                  :input_html => { :onchange => "admWeightControl(80)"},
                  :label => false
      = f.input :hmv,
                :input_html => { :class => "numeric" }
    #admWeight
      = f.input :adm_weight,
                :input_html => { :class => "numeric" }
  .span-24
    %fieldset#drg-proc
      %legend= t("fieldsets.diagnoses_procedures")
      #diagnoses
        = f.input :pdx,
                  :url => autocomplete_icd_code_path(version: @webgrouper_patient_case.system.icd_version),
                  :as => :autocomplete
        %label{:for => 'webgrouper_patient_case_diagnoses_0'}
          = t('simple_form.labels.defaults.diagnoses')  # hardcoded, since its generated via js
        = render "diagnoses", :patient_case => @webgrouper_patient_case
      %p
      #procedures
        %label{:for => 'webgrouper_patient_case_procedures_0_c'}
          = t('simple_form.labels.defaults.procedures')   # hardcoded, since its generated via js
        = render "procedures", :patient_case => @webgrouper_patient_case
  .buttons
    .right
      - unless @result.nil?
        = link_to t('helpers.submit.webgrouper_patient_case.save_case_as_bookmark'),
                   parse_url_for(@webgrouper_patient_case),
                   :class => 'button jQueryBookmark',
                   :title => "Webgrouper: #{@webgrouper_patient_case.pdx} #{Drg.get_description_for(@webgrouper_patient_case.system_id, @result.drg)}"
        = link_to image_tag('printer.png') + t('helpers.submit.webgrouper_patient_case.print_result'),
                  'javascript:printResult()', :class => 'button'
      = link_to t("help.show_help"), help_url, :class => 'button', :method => :get
      = link_to t("helpers.submit.webgrouper_patient_case.clear_form"), 
              webgrouper_patient_cases_path, 
              :class => "button negative", 
              :method => :get
      = f.submit :class => "button positive"
- if @result.nil? || @result.getGst.nil?         
  .bottom-spacer
- else  
  #result
    .span-15
      = render "webgrouper_patient_cases/result/grouping"
    .span-9.last
      - if normal_group?
        = render "webgrouper_patient_cases/result/cost_weight"
    - if normal_group?
      .span-24
        = render "webgrouper_patient_cases/result/diagnoses"
      .span-24
        = render "webgrouper_patient_cases/result/procedures"
      .span-24
        = render "webgrouper_patient_cases/result/settlement_hints"
      .span-8
        = render "webgrouper_patient_cases/result/length_of_stay"
      .span-16.last
        = render "webgrouper_patient_cases/result/los_chart"
    #bottom

app/views/webgrouper_patient_cases/index.html.haml
= content_for :header do
  = javascript_include_tag 'https://www.google.com/jsapi'
  = javascript_include_tag 'webgrouper'

= render "error_messages", :webgrouper_patient_case => @webgrouper_patient_case

= simple_form_for @webgrouper_patient_case, :url => :create_query, :method => :post do |f|
  = render 'shared/system', :f => f,
                            :current_system => @webgrouper_patient_case.system,
                            :house => @webgrouper_patient_case.house
  .on-row
    %fieldset#stay.left
      %legend= t("fieldsets.stay")
      = f.input :entry_date, 
                :input_html => { :title => t("simple_form.hints.webgrouper_patient_case.date"), :class => "date_picker calc_los" }
      = f.input :exit_date, 
                :input_html => { :title => t("simple_form.hints.webgrouper_patient_case.date"), :class => "date_picker calc_los" }
      = f.input :leave_days, 
                :input_html => { :class => "calc_los numeric" }
      = f.input :adm, 
                :as => :select, 
                :include_blank => false,
                :collection => ["11", "01", "06", "99"],
                :label_method => lambda { |el| t "simple_form.options.webgrouper_patient_case.adm.adm#{el}" }
      = f.input :sep, 
                :as => :select, 
                :include_blank => false,
                :collection => ["06","04","00","07","99"],
                :label_method => lambda { |el| t "simple_form.options.webgrouper_patient_case.sep.sep#{el}" }
      = f.input :los,
                :input_html => { :class => "numeric" }
  
    %fieldset#patient-data.right
      %legend= t("fieldsets.patient_data")
      = f.input :sex, 
                :collection => [:M , :W, :U], 
                :checked => :U, 
                :include_blank => false
      = f.input :birth_date, 
                :input_html => { :title => t("simple_form.hints.webgrouper_patient_case.date"), :class => "date_picker" }
      .sameline
        = f.input :age,
                  :input_html => { :class => "numeric" }
        = f.input :age_mode_decoy,
                  :as => :select, 
                  :collection => [:years, :days],
                  :include_blank => false, 
                  :input_html => { :onchange => "admWeightControl(80)"},
                  :label => false
        / hidden field which contains the real value for age_mode in case age_mode_decoy is disabled
        = f.input :age_mode,
                  :as => :hidden, 
                  :collection => [:years, :days],
                  :include_blank => false, 
                  :input_html => { :onchange => "admWeightControl(80)"},
                  :label => false
      = f.input :hmv,
                :input_html => { :class => "numeric" }
      #admWeight
        = f.input :adm_weight,
                  :input_html => { :class => "numeric" }

  %fieldset#drg-proc
    %legend= t("fieldsets.diagnoses_procedures")
    #diagnoses
      = f.input :pdx, 
                :url => autocomplete_Icd_code_webgrouper_patient_cases_path(:system_id => @webgrouper_patient_case.system_id), 
                :as => :autocomplete
      %label{:for => 'webgrouper_patient_case_diagnoses_0'}
        = t('simple_form.labels.defaults.diagnoses')  # hardcoded, since its generated via js
      = render "diagnoses", :patient_case => @webgrouper_patient_case
    %p
    #procedures
      %label{:for => 'webgrouper_patient_case_procedures_0_0'}
        = t('simple_form.labels.defaults.procedures')   # hardcoded, since its generated via js
      = render "procedures", :patient_case => @webgrouper_patient_case
  .buttons 
    .right
      - if @result
        = link_to t('helpers.submit.webgrouper_patient_case.save_case_as_bookmark'), current_case_url,
                   :class => 'button jQueryBookmark',
                   :title => "Webgrouper: #{@webgrouper_patient_case.pdx} #{Drg.get_description_for(@webgrouper_patient_case.system_id, @result.drg)}"
        = link_to image_tag('printer.png') + t('helpers.submit.webgrouper_patient_case.print_result'),
                  'javascript:printResult()', :class => 'button'
      = link_to t("help.show_help"), help_url, :class => 'button', :method => :get
      = link_to t("helpers.submit.webgrouper_patient_case.clear_form"), 
              webgrouper_patient_cases_path, 
              :class => "button negative", 
              :method => :get
      = f.submit :class => "button positive"
- if @result.nil? || @result.getGst.nil?         
  .bottom-spacer
- else  
  = render "webgrouper_patient_cases/result/main"

app/views/webgrouper_patient_cases/new.html.haml
%h1 Webgrouper


= render "shared/error_messages", :webgrouper_patient_case => @webgrouper_patient_case

= simple_form_for @webgrouper_patient_case do |f|
  %fieldset
    System stuff
  %fieldset
    = f.input :sex, :label => "#{t_label 'sex'}", :collection => [["#{t_label 'sex_male'}", "M"], ["#{t_label 'sex_female'}", "W"], ["#{t_label 'sex_unknown'}", "U"]], :checked => "U", :include_blank => false
    .sameline
      = f.input :age, :label => "#{t_label 'age'}"
      = f.input :age_mode, :label => "#{t_label 'age_mode'}", :as => :select, :collection => [["#{t_label 'years'}", "years"], ["#{t_label 'days'}", "days"]], :include_blank => false, :input_html => { :onchange => "admWeightControl(500)" }
    = f.input :birth_date, :label => "#{t_label 'birth_date'}", :input_html => { :class => "date_picker" }
    #admWeight
      = f.input :adm_weight, :label => "#{t_label 'adm_weight'}"
  %fieldset 
    = f.input :entry_date, :label => "#{t_label 'entry_date'}", :input_html => { :class => "date_picker calc_los" }
    = f.input :exit_date, :label => "#{t_label 'exit_date'}", :input_html => { :class => "date_picker calc_los" }
    = f.input :leave_days, :label => "#{t_label 'leave_days'}", :input_html => { :class => "calc_los" }
    = f.input :adm, :label => "#{t_label 'adm'}", :as => :select, :collection => %w(11 00 06 99), :include_blank => false
    = f.input :sep, :label => "#{t_label 'sep'}", :as => :select, :collection => %w(06 04 00 07 99), :include_blank => false
    = f.input :los, :label => "#{t_label 'los'}"
  %fieldset
    = f.input :sdf, :label => "#{t_label 'sdf'}"
    = f.input :hmv, :label => "#{t_label 'hmv'}"
    = f.input :pdx, :label => "#{t_label 'pdx'}"
    = f.input :diagnoses, :label => "#{t_label 'diagnoses'}"
    = f.input :procedures, :label => "#{t_label 'procedures'}"
  = f.submit "#{t_label 'group'}"
  
%h2 Gruppierung
%p= @result

app/views/webgrouper_patient_cases/parse.html.haml
%h2
  = t '.parse_patient_cases'
= t '.parse_patient_cases_description'
= simple_form_for @webgrouper_patient_case_parsing, :url => parse_webgrouper_patient_cases_path, :method => :post do |f|
  = render 'shared/system', f: f, current_system: @webgrouper_patient_case_parsing.system,
  house: @webgrouper_patient_case_parsing.house
  %fieldset
    %legend Input
    = f.input :parse_string, label: false, input_html: { style: 'width: 100%;'}
  .right
    = f.submit :class => "button positive", :value => 'Submit'