config/routes.rb
Webgrouper::Application.routes.draw do

  resources :statistics, only: :index do
    collection do
      get 'webgrouper_patient_cases'
      get 'batchgrouper_queries'
      get 'webapi_queries'
      get 'tarpsy_patient_cases'
      get 'tarpsy_batchgrouper_queries'
    end
  end

  scope "/:locale" do
    resources :webgrouper_patient_cases, only: [:index, :new, :create] do
      collection do
        patch '/' => 'webgrouper_patient_cases#create'
        match 'parse', via: [:get, :post]
      end
    end
    resources :tarpsy_patient_cases, only: [:index, :new, :create] do
      collection do
        patch '/' => 'tarpsy_patient_cases#create'
        get 'generate_random' => 'tarpsy_patient_cases#generate_random'
      end
    end
    resources :tarpsy_batchgrouper_queries, only: [:index, :new, :create] do
      collection do
        patch '/' => 'tarpsy_batchgrouper_queries#create'
      end
    end
    resources :batchgrouper_queries, only: [:index, :new, :create] do
      collection do
        patch '/' => 'batchgrouper_queries#create'
      end
    end
    match 'parse' => 'webgrouper_patient_cases#parse', via: [:get, :post]
    get 'help' => 'static_pages#help'
    get 'tos' => 'static_pages#tos'
    get 'autocomplete_icd_code' => 'webgrouper_patient_cases#autocomplete_icd_code'
    get 'autocomplete_chop_code' => 'webgrouper_patient_cases#autocomplete_chop_code'
  end

  resources :webapi_queries, path: 'webapi', as: 'webapi', only: [:index, :create] do
    collection do
      match 'group', via: [:get, :post]
      match 'systems', via: [:get, :post]
    end
  end

  get 'grouper' => 'batchgrouper_queries#tos'
  get 'activate_beta' => 'webgrouper_patient_cases#activate_beta'
  get 'batchgrouper' => 'batchgrouper_queries#tos'
  get 'webgrouper' => 'webgrouper_patient_cases#tos'
  get 'about' => 'static_pages#about'

  # Visitors of tarps.swissdrg.org should be redirected to tarpsy form.
  constraints subdomain: 'tarpsy' do
    get '/' => 'tarpsy_patient_cases#tos'
  end

  root :to => 'webgrouper_patient_cases#tos'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404', via: [:get, :post]
  end
end

app/models/webapi_query.rb
# For logging queries to the webapi
class WebapiQuery
  include Mongoid::Document
  belongs_to :system, primary_key: :system_id

  field :ip, type: String
  field :system_id, type: Integer
  field :input_format, type: String
  field :output_format, type: String
  field :user_agent, type: String
  field :start_time, type: Time
  field :finished_parsing_time, type: Time
  field :end_time, type: Time
  field :nr_cases, type: Integer
  field :error, type: String

  index :start_time => 1
end

app/controllers/webapi_queries_controller.rb
class WebapiQueriesController < ApplicationController

  def index
  end

  # Legacy, just do create action.
  def group
    create
  end

  def create
    system_id = params[:system] ||= 9
    unless System.exists?(system_id)
      system_id = 9
    end

    log_entry = WebapiQuery.create!(ip: request.remote_ip, system_id: system_id,
                                    input_format: params[:input_format], output_format: request.format,
                                    start_time: Time.now, user_agent: request.env['HTTP_USER_AGENT'])
    response = []
    begin
      pcs = PatientCaseParser.new(params).result
      log_entry.update_attributes!(nr_cases: pcs.size, finished_parsing_time: Time.now)
      pcs.each do |pc|
        grouper, catalogue = log_entry.system.grouper_and_catalogue
        grouper.groupByReference(pc)
        result = pc.getGrouperResult()
        wr = catalogue.get(result.drg)
        effective_cost_weight = grouper.calculateEffectiveCostWeight(pc, wr)
        response << WebapiResponse.new(result, pc, effective_cost_weight, system_id).result
      end
    rescue Exception => e
      log_entry.update_attributes!(error: e.message)
      raise e if Rails.env == 'development' #dont catch in development mode
      response = {:Error => e.message}
    end
    log_entry.update_attributes!(end_time: Time.now)
    respond_to do |format|
      format.xml {render :xml => response}
      format.json {render :json => response}
    end
  end

  def systems
    systems_hash = System.all_public.to_a.map {|s| { :name => s["description"]["de"], :id => s["system_id"] } }
    respond_to do |format|
      format.xml {render :xml => systems_hash}
      format.json {render :json => systems_hash}
    end
  end
end

app/views/webapi_queries/index.html.erb
<div id="header">
  <div id="header_inner" class="fixed">
    <div id="logo"><h1>SwissDRG Grouper WebAPI</h1></div>
    <div id="menu">

    </div>
  </div>
</div>

<div id="main">
  <br class="clear"/>

  <div id="main_inner" class="fixed">
    <div class="highlight">
      <h2>UPDATE: Arrays</h2>
      It is now possible to parse up to 1000 cases at once using any format. Accordingly, the syntax has changed as
      follows:
      <h3>Swissdrg</h3>
      The newline character is used to separate cases.
      <h3>XML</h3>
      The whole file has to be surrounded with &lt;Array&gt; ... &lt;/Array&gt;.
      You may have an arbitrary number (under 1000) of &lt;PatientCase&gt; nodes inside. The structure of a single &lt;PatientCase&gt;
      node did not change.
      <h3>JSON</h3>
      The data must be passed as JSON array (meaning surrounded by [ .. ] ). You may have an arbitrary number (under
      1000) json objects inside.
      The structure of a single JSON object did not change.
      <h3>Output</h3>
      The output will also be returned as an array.
    </div>
    </br>
    The WebAPI for the SwissDRG grouper consists of two actions (either GET or POST):<br/>
    <ul>
      <li>
        <%= link_to 'webapi/systems (.xml|.json)', systems_webapi_index_path(:format => 'xml') %>
        Get a list with all available systems.
      </li>
      <li>
        <%= link_to 'webapi/group (.xml|.json)', webapi_index_path(:format => 'xml') %>
        Group a patient case. The parameters and the output are desrcibed bellow.
      </li>
    </ul>

    <span style="font-weight:bold">Parameters for group:</span><br/>
    system: (default: 9) id of system to group with <br/>
    format: output format (<u>xml</u>|json)<br/>
    input_format: input format (<u>swissdrg</u>|xml|json)<br/>
    pc: patient case in the format specified in input_format<br/>
    <br/>
    <span style="font-weight:bold">Response:</span><br/>
    The response is a nested hash containing an entry for "PatientCase" which is the input patient case with the
    calculated length of stay and age,
    an entry for "GrouperResult" containing the grouping results (drg, mdc), an entry for the effective cost weight
    and an entry with the id of the used system.<br/>
    If your input is not valid json, xml or swissdrg or some information is missing, the response contains an "Error"
    entry describing the problem.<br/>

    <form action="<%= webapi_index_path(:format => 'xml') %>" method="post">
      <p><b>SwissDRG Input, XML Output</b><br><textarea name="pc" cols="70" rows="10"></textarea>
        <input type="hidden" name="input_format" value="swissdrg"/><input type="submit" value="Go"></p>
    </form>
    Example Input: See
    <a href="https://webgrouper.swissdrg.org/webapi/grouper-doku-de.pdf">Documentation for the SwissDRG Input Format</a><br/>
    for further information.
    59;0;27;;W;11;00;48;;;P072;;;;P071;;;;R068;;R001;;P612;;H351;;P742;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;966;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
    <br/><br/>

    <form action="<%= webapi_index_path(:format => 'json') %>" method="post">
      <p><b>SwissDRG Input, JSON Output</b><br><textarea name="pc" cols="70" rows="10"></textarea>
        <input type="hidden" name="input_format" value="swissdrg"/><input type="submit" value="Go"></p>
    </form>

    <form action="<%= webapi_index_path(:format => 'xml') %>" method="post">
      <p><b>JSON Input, XML Output</b><br><textarea name="pc" cols="70" rows="10"></textarea>
        <input type="hidden" name="input_format" value="json"/><input type="submit" value="Go"></p>
    </form>
    Example JSON Input:
<pre>
[{"id":"342559",
 "entryDate":"00000000",
 "exitDate":"00000000",
 "birthDate":"00000000",
 "leaveDays":0,
 "ageYears":0,
 "ageDays":27,
 "admWeight":0,
 "sex":"W",
 "adm":"11",
 "sep":"00",
 "los":48,
 "hmv":0,
 "pdx":"P072",
 "diagnoses":["P071","P920","R068","R001","P612","H351"],
 "procedures":["966"]}
  ]
</pre>
    <br/><br/>

    <form action="<%= webapi_index_path(:format => 'json') %>" method="post">
      <p><b>JSON Input, JSON Output</b><br><textarea name="pc" cols="70" rows="10"></textarea>
        <input type="hidden" name="input_format" value="json"/>
        <input type="submit" value="Go"></p>
    </form>

    <form action="<%= webapi_index_path(:format => 'xml') %>" method="post">
      <p><b>XML Input, XML Output</b><br><textarea name="pc" cols="70" rows="10"></textarea>
        <input type="hidden" name="input_format" value="xml"/>
        <input type="submit" value="Go"></p>
    </form>

    Example XML Input:
<pre>
&lt;Array&gt;
	&lt;PatientCase&gt;
	    &lt;id&gt;3455259&lt;/id&gt;
	    &lt;entryDate&gt;00000000&lt;/entryDate&gt;
	    &lt;exitDate&gt;00000000&lt;/exitDate&gt;
	    &lt;birthDate&gt;00000000&lt;/birthDate&gt;
	    &lt;leaveDays type=&quot;integer&quot;&gt;0&lt;/leaveDays&gt;
	    &lt;ageYears type=&quot;integer&quot;&gt;0&lt;/ageYears&gt;
	    &lt;ageDays type=&quot;integer&quot;&gt;27&lt;/ageDays&gt;
	    &lt;admWeight type=&quot;integer&quot;&gt;0&lt;/admWeight&gt;
	    &lt;sex&gt;W&lt;/sex&gt;
	    &lt;adm&gt;11&lt;/adm&gt;
	    &lt;sep&gt;00&lt;/sep&gt;
	    &lt;los type=&quot;integer&quot;&gt;48&lt;/los&gt;
	    &lt;hmv type=&quot;integer&quot;&gt;0&lt;/hmv&gt;
	    &lt;pdx&gt;P072&lt;/pdx&gt;
	    &lt;diagnoses type=&quot;array&quot;&gt;
	        &lt;diagnosis&gt;P071&lt;/diagnosis&gt;
	        &lt;diagnosis&gt;P920&lt;/diagnosis&gt;
	        &lt;diagnosis&gt;R068&lt;/diagnosis&gt;
	        &lt;diagnosis&gt;R001&lt;/diagnosis&gt;
	        &lt;diagnosis&gt;P612&lt;/diagnosis&gt;
	        &lt;diagnosis&gt;P928&lt;/diagnosis&gt;
	    &lt;/diagnoses&gt;
	    &lt;procedures type=&quot;array&quot;&gt;
	        &lt;procedure&gt;966&lt;/procedure&gt;
	    &lt;/procedures&gt;
	&lt;/PatientCase&gt;
&lt;/Array&gt;
</pre>
    <br/><br/>

    <form action="<%= webapi_index_path(:format => 'json') %>" method="post">
      <p><b>XML Input, JSON Output</b><br><textarea name="pc" cols="70" rows="10"></textarea>
        <input type="hidden" name="input_format" value="xml"/><input type="submit" value="Go"></p>
    </form>
  </div>
  <br class="clear"/>
</div>