config/routes.rb
Webgrouper::Application.routes.draw do

  resources :statistics, only: :index do
    collection do
      get 'webgrouper_patient_cases'
      get 'batchgrouper_queries'
      get 'webapi_queries'
      get 'tarpsy_patient_cases'
      get 'tarpsy_batchgrouper_queries'
    end
  end

  scope "/:locale" do
    resources :webgrouper_patient_cases, only: [:index, :new, :create] do
      collection do
        patch '/' => 'webgrouper_patient_cases#create'
        match 'parse', via: [:get, :post]
      end
    end
    resources :tarpsy_patient_cases, only: [:index, :new, :create] do
      collection do
        patch '/' => 'tarpsy_patient_cases#create'
        get 'generate_random' => 'tarpsy_patient_cases#generate_random'
      end
    end
    resources :tarpsy_batchgrouper_queries, only: [:index, :new, :create] do
      collection do
        patch '/' => 'tarpsy_batchgrouper_queries#create'
      end
    end
    resources :batchgrouper_queries, only: [:index, :new, :create] do
      collection do
        patch '/' => 'batchgrouper_queries#create'
      end
    end
    match 'parse' => 'webgrouper_patient_cases#parse', via: [:get, :post]
    get 'help' => 'static_pages#help'
    get 'tos' => 'static_pages#tos'
    get 'autocomplete_icd_code' => 'webgrouper_patient_cases#autocomplete_icd_code'
    get 'autocomplete_chop_code' => 'webgrouper_patient_cases#autocomplete_chop_code'
  end

  resources :webapi_queries, path: 'webapi', as: 'webapi', only: [:index, :create] do
    collection do
      match 'group', via: [:get, :post]
      match 'systems', via: [:get, :post]
    end
  end

  get 'grouper' => 'batchgrouper_queries#tos'
  get 'activate_beta' => 'webgrouper_patient_cases#activate_beta'
  get 'batchgrouper' => 'batchgrouper_queries#tos'
  get 'webgrouper' => 'webgrouper_patient_cases#tos'
  get 'about' => 'static_pages#about'

  # Visitors of tarps.swissdrg.org should be redirected to tarpsy form.
  constraints subdomain: 'tarpsy' do
    get '/' => 'tarpsy_patient_cases#tos'
  end

  root :to => 'webgrouper_patient_cases#tos'

  unless Rails.application.config.consider_all_requests_local
    match '*not_found', :to => 'errors#error_404', via: [:get, :post]
  end
end

app/models/batchgrouper_query.rb
# For logging queries to the batchgrouper
class BatchgrouperQuery
  include Mongoid::Document
  include Mongoid::Timestamps

  field :output_file_path, type: String
  field :house, type: Integer

  field :ip, type: String
  field :client, type: String
  field :first_line, type: String
  field :line_count, type: Integer
  field :archived, type: Boolean, default: false

  validates_presence_of :input, unless: :archived
  validates_presence_of :house, :ip, :system_id
  validates_inclusion_of :house, in: [1, 2]
  validates_with BatchgrouperInputValidator, field_name: :input

  belongs_to :system, primary_key: :system_id

  mount_uploader :input, BatchgrouperInputUploader

  after_initialize :set_defaults
  before_destroy :delete_output

  index created_at: 1

  def group
    # TODO: Log first_line, line_count
    update_attribute(:output_file_path, input.file.path + '.out')
    args = {'input-format' => 'batch',
            'output-format' => 'batch',
            'output-file' => output_file_path,
    }
    # Depending house variable, use catalogue for birthhouses or hospitals
    if house == 1
      args.merge!('drg-catalogue' => self.system.catalogue)
    else
      args.merge!('birthouse' => nil, 'drg-catalogue' => self.system.birthhouse_catalogue)
    end

    # Insert quotes where necessary.
    args_string = args.map {|k, v| "--#{k} #{v.nil? ? '' : Shellwords.escape(v)}"}.join(' ')
    trailing_args_string = "#{Shellwords.escape(self.system.workspace)} #{Shellwords.escape(self.input.file.path)}"
    # Start grouper
    grouper_command = "java -jar #{Rails.root.join('lib', 'grouper.jar')} #{args_string} #{trailing_args_string}"
    Rails.logger.debug(grouper_command)
    grouper_output = `#{grouper_command}`
    Rails.logger.info(grouper_output)
    grouper_output
  end

  def group_line(line)
    # TODO
  end

  def archive!
    delete_output
    remove_input!
    self.archived = true
    save!
  end


  private

  def set_defaults
    self.system_id ||= System::DEFAULT_SYSTEM_ID
  end

  def delete_output
    if output_file_path and File.exists?(output_file_path)
      FileUtils.rm self.output_file_path
    end
  end
end

app/controllers/batchgrouper_queries_controller.rb
class BatchgrouperQueriesController < ApplicationController
  def tos
    @link = new_batchgrouper_query_path
    render 'static_pages/tos'
  end

  def index
    redirect_to new_batchgrouper_query_path
  end

  def new
    @batchgrouper_query = BatchgrouperQuery.new
    render 'form'
  end

  def create
    @batchgrouper_query = BatchgrouperQuery.create(batchgrouper_query_params.merge(ip: request.remote_ip,
                                                                                   client: request.env['HTTP_USER_AGENT']))
    unless @batchgrouper_query.errors.any?
      @batchgrouper_query.group
      cookies[:download_finished] = true
      return send_file @batchgrouper_query.output_file_path, content_type: Mime::CSV
    end
    render 'form'
  end

  private

  def batchgrouper_query_params
    params[:batchgrouper_query].permit(:input, :system_id, :house)
  end
end

app/views/batchgrouper_queries/_hint_documentation.de.html.haml
Eine Dokumentation zum Batchgrouper und eine Beschreibung zu den Formaten finden Sie hier: 
= link_to "Grouper-Dokumentation", "https://webgrouper.swissdrg.org/grouper/grouper-doku-de.pdf"

app/views/batchgrouper_queries/_hint_documentation.en.html.haml
You find the documentation of the Batch grouper and a description 
of the used formats here: 
= link_to "Grouper-documentation", "https://webgrouper.swissdrg.org/grouper/grouper-doku-de.pdf"

app/views/batchgrouper_queries/_hint_documentation.fr.html.haml
Une documentation pour le batchgrouper et une description
des formats sont à votre disposition: 
= link_to "Documentation du Grouper", "https://webgrouper.swissdrg.org/grouper/grouper-doku-fr.pdf"

app/views/batchgrouper_queries/_hint_documentation.it.html.haml
Una documentazione per il batchgrouper e una descrizione dei formati
sono a vostra disposizione:
= link_to "Documentazione del Grouper", "https://webgrouper.swissdrg.org/grouper/grouper-doku-it.pdf"

app/views/batchgrouper_queries/form.html.haml
- content_for :header do
  = javascript_include_tag 'batchgrouper_query'
- content_for :title, 'Batchgrouper'
= simple_form_for @batchgrouper_query, :url => batchgrouper_queries_path do |f|
  - if flash[:error]
    .errorflash
      = flash[:error].html_safe
  = render 'batchgrouper_queries/hint_documentation'
  = render "shared/system", :f => f, :current_system => @batchgrouper_query.system, :house => @batchgrouper_query.house
  %fieldset
    %legend Data
    = f.input :input
  #loading
    = t "batchgrouper.loading_hint"
    #loading-bar
  = link_to t('simple_form.labels.batchgrouper_query.single_group'), parse_webgrouper_patient_cases_path
  .right
    = f.submit :class => "button positive"